# Generated by Django 4.2.9 on 2025-04-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[
                    ("To Do", "To Do"),
                    ("In Progress", "In Progress"),
                    ("Done", "Done"),
                ],
                default="In Progress",
                max_length=50,
            ),
        ),
    ]
