# Generated by Django 4.2.20 on 2025-04-20 16:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_alter_todo_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
